apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-frontend
  template:
    metadata:
      labels:
        app: sentiment-frontend
    spec:
      containers:
      - name: sentiment-frontend
        image: kaushal11/sentiment-frontend
        ports:
        - containerPort: 80
